[package]
name = "building_model"
version = "0.1.0"
authors = ["German Molina <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometry3d = {path = "../geometry3d"}
calendar = { path = "../calendar" }
schedule = { path = "../schedule" }
building_state_macro = {path="../building_state_macro"}

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.2"

[[bench]]
name = "benchmark"
harness = false