[package]
name = "building_model"
version = "0.1.0"
authors = ["German Molina <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geometry3d = {path = "../geometry3d"}
simulation_state = { path = "../simulation_state" }
