name: Docs

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - name: Set Toolchain
      run: rustup default nightly
    - name: Install MDBook
      run: cargo install mdbook
    - name: Install MDBook Katex
      run: cargo install mdbook-katex
    - name: Run tests # This creates the IO docs
      run: cargo test --verbose     
    - name: Build Book
      run: mdbook build ./docs/ioreference
    - name: Build doc
      run: RUSTDOCFLAGS="--html-in-header katex.html" cargo doc --document-private-items --no-deps --target-dir ./docs/rustdoc
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
  
