name: IOReference

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2        
    - name: Install MDBook
      run: cargo install mdbook
    - name: Install MDBook Katex
      run: cargo install mdbook-katex
    - name: Build Book
      run: mdbook build ioreference
    - name: Build docs
      run: cargo doc --document-private-items --no-deps --target-dir ./ioreference/src
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ioreference/book # The folder the action should deploy.